version: "3"

services:
  # nginx:
  #   container_name: "nginx"
  #   image: "nginx"
  #   volumes:
  #     - ./etc/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - app

  # app:
  #   container_name: app
  #   build:
  #     context: "../"
  #     dockerfile: "./docker/Dockerfile"
  #   environment:
  #     - OTEL_SERVICE_NAME=app
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317 # http://localhost:4317
  #     - OTEL_EXPORTER_OTLP_INSECURE=true
  #     - OTEL_METRICS_EXPORTER=otlp
  #     - OTEL_TRACES_EXPORTER=none
  #     - OTEL_LOGS_EXPORTER=none
  #     # - OTEL_METRIC_EXPORT_INTERVAL=1000
  #     - COLLECTOR_OTLP_ENABLED=true
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - otel-collector

  otel-collector:
    container_name: "otel-collector"
    image: "otel/opentelemetry-collector-contrib"
    volumes:
      - ./etc/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 8888:8888 # Prometheus metrics exposed by collector
      - 8889:8889 # Prometheus exporter metrics

  prometheus:
    container_name: "prometheus"
    image: "prom/prometheus"
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    container_name: "grafana"
    image: "grafana/grafana"
    ports:
      - 3000:3000
