version: "3"

services:
  nginx:
    container_name: "nginx"
    image: "nginx"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  app:
    container_name: app
    build:
      context: "../"
      dockerfile: "./docker/Dockerfile"
    environment:
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_PYTHON_LOG_FORMAT="%(msg)s [span_id=%(span_id)s]"
      - OTEL_SERVICE_NAME=app
      - OTEL_METRIC_EXPORT_INTERVAL=1000
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_PYTHON_LOG_LEVEL=debug
      - OTEL_PYTHON_LOG_CORRELATION=true
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 8000:8000

  otel-collector:
    container_name: "otel-collector"
    image: "prom/prometheus"
    volumes:
      - ./etc/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml

  prometheus:
    container_name: "prometheus"
    image: "prom/prometheus"
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    container_name: "grafana"
    image: "grafana/grafana"
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana

volumes:
  grafana_storage: {}
